configuration: Release
init:
  - git config --global core.autocrlf true
before_build:
  - dotnet restore
build:
  verbosity: minimal
environment:
  global:
    DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
    DOTNET_CLI_TELEMETRY_OPTOUT: 1
test: on
deploy: off
os: Visual Studio 2017